#!/bin/sh
# Just a simple runner for the gearificator'ed interface.
#
# All needed information should be specified via manifest.conf and config.json 

set -eu
. /etc/fsl/fsl.sh
python -m gearificator "$@"
